[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "gradio>=5.29.0",
    "keras>=3.9.2",
    "numpy>=2.2.5",
    "uvicorn>=0.34.2",
]
